server:
  port: 8765

spring:
  application:
    name: APIGateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/user/**
        - id: admin-service
          uri: http://localhost:8081
          predicates:
            - Path=/admin/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

