server:
  port: 8765

spring:
  application:
    name: GateWayApi

  cloud:
    gateway:
      routes:
        - id: UserService
          uri: http://localhost:8082
          predicates:
            - Path=/user/**
        - id: AdminService
          uri: http://localhost:8081
          predicates:
            - Path=/admin/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka


